core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('list/', views.CompanyList.as_view(), name='list'),
    path('new/', views.import_data, name="new"),
    path('view/<int:pk>', views.CompanyView.as_view(), name='view'),
    path('edit/<int:pk>', views.CompanyUpdate.as_view(), name='edit'),
    path('delete/<int:pk>', views.CompanyDelete.as_view(), name='delete'),
    path('', views.SaletListView.as_view(), name='list_all'),

]

sales/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name="logout"),
]

core/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField('Name', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'
        ordering = ['name']


class Category(models.Model):
    name = models.CharField('Name', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['name']


class Sale(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    product = models.CharField('Products', max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    units_sold = models.CharField('Units Sold', max_length=100)
    cost_price = models.CharField('Cost Sale', max_length=100)
    total_sale = models.CharField('Total Sale', max_length=100)

    def __str__(self):
        return self.product

    class Meta:
        verbose_name = 'Sale'
        verbose_name_plural = 'Sales'
        ordering = ['company']

core/forms.py
from django import forms
from django.core.validators import FileExtensionValidator


class UploadFileForm(forms.Form):
    
    company = forms.CharField(label='Empresa')
    email = forms.EmailField(label='E-mail')
    file = forms.FileField(validators=[
        FileExtensionValidator(['xlsx', 'xls'])]
        )

core/views.py
import os
import uuid

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.http import HttpResponseBadRequest
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from .models import Company, Sale
from .forms import UploadFileForm
from .jobs import parse_sales_job


class SaletListView(LoginRequiredMixin, ListView):

    template_name = 'core/sales_list_all.html'
    context_object_name = 'sales'
    paginate_by = 50

    def get_queryset(self):
        queryset = Sale.objects.all()
        return queryset


class CompanyList(LoginRequiredMixin, ListView):
    model = Company


class CompanyView(LoginRequiredMixin, DetailView):
    model = Company
    context_object_name = 'company'


class CompanyCreate(LoginRequiredMixin, CreateView):
    model = Company
    fields = ['name']
    success_url = reverse_lazy('new')


class CompanyUpdate(LoginRequiredMixin, UpdateView):
    model = Company
    fields = ['name']
    success_url = reverse_lazy('list')


class CompanyDelete(LoginRequiredMixin, DeleteView):
    model = Company
    success_url = reverse_lazy('list')


def import_data(request):
    success = False

    form = UploadFileForm(request.POST,
                            request.FILES)

    if form.is_valid():
        company_name = form.cleaned_data['company']
        email = form.cleaned_data['email']
        spreadsheet = request.FILES.get('file')
        root_name, ext = os.path.splitext(spreadsheet.name)
        basename = '%s.%s' % (uuid.uuid1(), ext)

        spreadsheet_destiny = os.path.join(
            settings.SPREADSHEET_FILES_PATH,
            basename
        )
        with open(spreadsheet_destiny, 'wb') as f:
            f.write(spreadsheet.read())

        parse_sales_job(company_name, email, basename)

        send_mail(
            'Suas vendas estão sendo processadas',
            """O arquivo de vendas da empres %s foi adicionado
             na fila de processamento""" % company_name,
            'no-reply@vendas.com',
            [ email ]
        )
        messages.info(request, 'Suas vendas estão sendo processadas')
    elif request.method == 'POST':
        messages.error(request, 'Formulário inválido')

    return render(

        request,
        'core/upload_form.html',
        {
            'form': form,
            'success': success,
        })

core/templates/base.html
{% load static %}
<html lang="en">
<title>{% block title %}Django Sales{% endblock %}</title>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
<!-- Fixed navbar -->

<body>
    {% if user.is_authenticated %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom shadow-sm navbar-dark bg-dark ">
        <h5 class="my-0 text-white mr-md-auto font-weight-normal"> <a href="{% url 'list_all' %}"> Sistema </a></h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-white" href="{% url 'list' %}">Empresas</a>
            <a class="p-2 text-white" href="{% url 'list_all' %}">Vendas & Empresas</a>
        </nav>
        <a class="btn btn-outline-primary" href="{% url 'logout' %}">Sair</a>
        {% endif %}
    </div>
    <br>
    <br>
</body>
<div class="container">
    {% block messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
        </div>
    {% endfor %} {% endblock %} {% block container %} {% endblock %}
</div>
</main>

<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/style.js' %}"></script>

</body>
{% block js %} {% endblock %}

core/templates/core/company_confirm_delete.html
{% extends "base.html" %} {% load i18n static %} {% block container %}
<div class="container">
    <h2>Remover Cadastro</h2>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" class="btn btn-danger" value="Delete" />
    </form>
</div>

{% endblock %}

core/templates/core/company_detail.html
{% extends "base.html" %} {% load i18n static %} {% block container %}
<div class="container">
  <h2>Empresa : {{object.name}}</h2><br><br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Produtos</th>
        <th scope="col">Categorias</th>
        <th scope="col">Unidades vendidas no mês</th>
        <th scope="col">Preço de custo</th>
        <th scope="col">Total da venda</th>
      </tr>
    </thead>
    <tbody>
      {% for sale in company.sale_set.all %}
      <tr>
        <td id="product">{{sale.product}}</td>
        <td>{{sale.category}}</td>
        <td>{{sale.units_sold}}</td>
        <td>{{sale.cost_price}}</td>
        <td>{{sale.total_sale}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

core/templates/core/company_form.html
{% extends "base.html" %} {% load i18n static %} {% block container %}
<div class="container">
    <form action="" enctype="multipart/form-data" method="post">
        {{ form.as_table }} {% csrf_token %}
        <br>
        <br>
        <button class="btn btn-success" type="submit" value="Upload">Salvar</a>
    </form>
</div>

{% block body %} {% endblock %} {% endblock %}

core/templates/core/company_list.html
{% extends "base.html" %} {% load i18n static %} {% block container %}
<main role="main" class="container">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Empresa</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
      </tr>
    </thead>

    <tbody>
      {% for sale in object_list %}
      <tr>
        <td>{{sale.name}}</td>
        <td><a href="{% url "view" sale.id %}">view</a></td>
        <td><a href="{% url "edit" sale.id %}">edit</a></td>
        <td><a href="{% url "delete" sale.id %}">delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <a class="btn btn-success" href="{% url "new" %}">Novo</a>
</main>
{% endblock %}

core/templates/core/sales_list_all.html
{% extends "base.html" %} {% load i18n static %} {% load pagination %} {% block container %}

<main role="main" class="container">
  <div class="starter-template">
    <a type="button" class="btn btn-primary" href="{% url 'new' %}">Novo cadastro</a>
    <br>
    <br>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Empresa</th>
          <th scope="col">Produtos</th>
          <th scope="col">Categorias</th>
          <th scope="col">Unidades vendidas no mês</th>
          <th scope="col">Preço de custo</th>
          <th scope="col">Total da venda</th>
        </tr>
      </thead>
      <tbody>
        {% for sale in sales %}
        <tr>
          <td><a href="{% url "view" sale.company_id %}">{{sale.company}}</a></td>
          <td>{{sale.product}}</td>
          <td>{{sale.category}}</td>
          <td>{{sale.units_sold}}</td>
          <td>{{sale.cost_price}}</td>
          <td>{{sale.total_sale}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% pagination request paginator page_obj %} {% endblock %}
  </div>
</main>

core/templates/core/upload_form.html
{% extends "base.html" %} {% load i18n static %} {% load widget_tweaks %} {% block container %}

<main role="main" class="container">
    <h1>Cadastrar</h1>

  <form action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <fieldset>
      {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
        <div class="col-md-9">
          {% render_field field class='form-control' %} {% for error in field.errors %}
          <span class="text-danger" >{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      {% endfor %}
      <div class="form-group">
        <div class="col-md-9 col-md-offset-3">
          <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
      </div>
    </fieldset>
  </form>

</main>
{% endblock %}

core/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %} Entra | {{ block.super }} {% endblock %}

{% block  container %}
<link href="{% static 'css/style.css' %}" rel="stylesheet" />

<div class="container">
        <div class="card card-container">
                <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
                <p id="profile-name" class="profile-name-card"></p>
                <form class="form-signin" method="post">
                        {% csrf_token %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <fieldset>
                            <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                              <label for="{{ form.username.auto_id }}" class="col-md-4 control-label">{{ form.username.label }}</label>
                              <div class="">
                                {% render_field form.username class="form-control" %}
                                {% for error in form.username.errors %}
                                <span class="help-block">{{ error }}</span>
                                {% endfor %}
                              </div>
                            </div>
                            <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                              <label for="{{ form.password.auto_id }}" class="col-md-4 control-label">{{ form.password.label }}</label>
                              <div class="">
                                {% render_field form.password class="form-control" %}
                                {% for error in form.password.errors %}
                                <span class="help-block">{{ error }}</span>
                                {% endfor %}
                              </div>
                            </div>
                            <div class="form-group">
                              <div class=" col-md-offset-6">
                                <button type="submit" class="btn btn-primary">Enviar</button>
                              </div>
                            </div>
                        </fieldset>
                    </form>
        </div>
</div>

{% endblock %}

core/templates/logout.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %} Entra | {{ block.super }} {% endblock %}

{% block  container %}
<div class="container">
    <p><a href="{% url 'login' %}">Acessar novamente</a></p>
</div>
{% endblock %}

core/templates/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% for page in paginator.page_range %}
        <li class="page-item" {% if page_obj.number == page %} class="active" {% endif %}><a class="page-link" href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
        {% endfor %}
    </ul>
</nav>